dependencies:
- alias: zeebe
  name: zeebe-cluster
  repository: "@payk-chart-museum"
  version: 0.3.0
- alias: operate
  name: zeebe-operate
  repository: "@payk-chart-museum"
  version: 0.2.0
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.19.0
